### ISSUE TITLE
Change of URL addresses for HBCI and FinTS (Umstellung URL-Adressen bei HBCI und FinTS)

### ISSUE THREAD

**Issue by SongPing** [libfintx/libfintx#14]
Today (2024-03-13) it seems that for many banks the HBCI/FinTs Url has changed.
So if you get some error, you have to change the HBCI/FinTs Urls:

This is needed for Volksbank, Badische Beamtenbank, Evangelische Bank, ....
https://hbci11.fiducia.de/cgi-bin/hbciservlet  =>  https://fints2.atruvia.de/cgi-bin/hbciservlet
https://hbci-pintan.gad.de/cgi-bin/hbciservlet => https://fints1.atruvia.de/cgi-bin/hbciservlet

For other banks there maybe a similar change ...

See: https://www.vbidr.de/firmenkunden/zahlungsverkehr/banking/umstellung_url_banking-software.html

**Comment by leo-schick** [comment]
@SongPing Thanks for the information! I created #15 which will fix this. Awaiting now code review from @torstenklement
